name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: 🚀 Build and Deploy
        uses: tlienart/xranklin-build-action@main
